version: '3.8'

services:
  database:
    build: 
      context: ./users_api/src/database/
      dockerfile: Dockerfile
    restart: always
    ports: 
      - 3300:3306
    environment:
      - MYSQL_ROOT_PASSWORD=123456

  users_api:
    build: 
      context: ./users_api/
      dockerfile: Dockerfile
    restart: always
    depends_on:
      - database
    ports:
      - 3000:3000
    environment:
      - HOST=database
    links:
      - database

  test_server:
    build: 
      context: ./users_api/test-server/
      dockerfile: Dockerfile
    restart: always
    depends_on:
      - users_api
    ports:
      - 8080:8080
    links:
      - users_api
